[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "REVM primitives"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm", "types"]
license = "MIT"
name = "revm-primitives"
repository = "https://github.com/bluealloy/revm"
version = "1.1.2"
readme = "../../README.md"

[dependencies]
alloy-primitives = { version = "0.3", default-features = false, features = ["rlp"] }
alloy-rlp = { version = "0.3", default-features = false, features = ["derive"] }
bytes = { version = "1.5", default-features = false }
hashbrown = "0.14"
primitive-types = { version = "0.12", default-features = false }
auto_impl = "1.1"
bitvec = { version = "1", default-features = false, features = ["alloc"] }
bitflags = { version = "2.4.0", default-features = false }

# For setting the CfgEnv KZGSettings. Enabled by std flag.
c-kzg = { git = "https://github.com/ethereum/c-kzg-4844", default-features = false, optional = true }

#utility
hex-literal = "0.4"
hex = { version = "0.4", default-features = false, features = ["alloc"]}
derive_more = "0.99"
enumn = "0.1"
once_cell = { version = "1.18", default-features = false }

# optional
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
arbitrary = { version = "1.3", features = ["derive"], optional = true }
proptest = { version = "1.1", optional = true }
proptest-derive = { version = "0.4", optional = true }

[dev-dependencies]
arbitrary = { version = "1.3", features = ["derive"] }
proptest = "1.1"
proptest-derive = "0.4"
ruint = { version = "1.10.1", features = [
    "primitive-types",
    "rlp",
    "proptest",
    "arbitrary",
] }

[build-dependencies]
hex = "0.4"

[features]
default = ["std"]
dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
]
memory_limit = []
no_gas_measuring = []
optional_balance_check = []
optional_block_gas_limit = []
optional_eip3607 = []
optional_gas_refund = []
optional_no_base_fee = []
std = [
    "alloy-primitives/std",
    "alloy-rlp/std",
    "bytes/std",
    "hex/std",
    "bitvec/std",
    "bitflags/std",
    "dep:c-kzg",
]
serde = [
    "dep:serde",
    "alloy-primitives/serde",
    "hex/serde",
    "hashbrown/serde",
    "bytes/serde",
    "bitvec/serde",
    "bitflags/serde",
]
arbitrary = [
    "std",
    "alloy-primitives/arbitrary",
    "dep:arbitrary",
    "dep:proptest",
    "dep:proptest-derive",
    "bitflags/arbitrary",
]
